server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maoyourabbit?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: 8.130.44.99
    port: 5672
    username: chen
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
qiniu:
  kodo:
    # 配置accessKey
    accessKey: 
    # 配置secretKey
    secretKey: 
    # 配置空间名称
    bucket: ershojiaoyi
    # 配置域名
    domain: rtx81msgm.hn-bkt.clouddn.com
# netty-socketio 配置
aliyun:
  sms:
    access+

socketio:
  host: 0.0.0.0
  port: 9000
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

